---
# tasks file for redmine

- include: apt.yml
- include: nginx.yml
- include: postgresql.yml
- include: unix.yml


- name: Ensure redmine dir's presented
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/redmine
    - "/opt/redmine/redmine-{{ redmine_version }}/tmp/pids/"

- include: fix_permissions.yml

- name: "Download redmine {{ redmine_version }}"
  get_url:
    url: "http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz"
    dest: "/opt/redmine/redmine-{{ redmine_version }}.tar.gz"
  register: DownloadRedmineTGZ


- name: Unpack redmine
  sudo: no
  shell: >
    cd /opt/redmine && tar xfzv redmine-{{ redmine_version }}.tar.gz
  args:
    executable: /bin/bash

# - name: Unpack redmine
#   unarchive:
#     src: "/opt/redmine/redmine-{{ redmine_version }}.tar.gz"
#     dest: /opt/redmine
#     remote_src: yes
#   when: DownloadRedmineTGZ.changed


- include: fix_permissions.yml
- include: redmine_init.yml
- include: sidekiq.yml

- include: centosadmin_plugins.yml
  with_items:
    - redmine_telegram_common
    - redmine_intouch

- name: Copy sidekq configuration
  copy:
    src: "/opt/redmine/redmine-{{ redmine_version }}/plugins/redmine_intouch/extras/sidekiq.yml"
    dest: "/opt/redmine/redmine-{{ redmine_version }}/config"
    remote_src: true

- include: place_service.yml
  with_items:
    - redmine
    - redmine-bot
    - sidekiq

- include: service_autostart.yml
  with_items:
    - redmine
    - redis-server
    - sidekiq
    - redmine-bot

- include: start_service.yml
  with_items:
    - redmine
    - redis-server
    - sidekiq
    - redmine-bot

