---

- name: Purge default site nginx configuration
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/nginx/sites-enabled/default
    -  /etc/nginx/sites-available/default
  when: nginx_installation.changed

- name: Place nginx redmine configuration
  template:
    src: redmine.conf
    dest: "/etc/nginx/sites-available/{{ domain }}"
  register: nginx_redmine

- name: Place symbolic link to redmine
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"

- name: Reload nginx
  service:
    name: nginx
    state: reloaded